services:
  db:
    hostname: db
    image: postgres:17.5
    env_file:
      - .env
    volumes:
      - ${PWD}/.db-data/:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - db-net
      
  api:
    build:
      context: ${PWD}/api/
      dockerfile: Containerfile
    env_file:
      - .env
    volumes:
      - ${PWD}/api/:/api
    networks:
      - db-net
    ports:
      - "8000:8000"
    depends_on:
      - db

  mgr:
    build:
      context: ${PWD}/mgr/
      dockerfile: Containerfile
    privileged: true
    env_file:
      - .env
    volumes:
      - ${PWD}/mgr/:/mgr
    networks:
      - db-net
    depends_on:
      - db

networks:
  db-net:
    driver: bridge