user nginx;
worker_processes  1;
error_log  logs/error.log  notice;
pid        logs/nginx.pid;
include modules.d/*.conf;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    types_hash_max_size 4096;
    default_type  application/octet-stream;
    access_log  logs/access.log;
    keepalive_timeout  65;
    gzip  on;


    # HTTP → redirect to HTTPS
    server {
        listen      80;
        server_name localhost;

        location / {
            return 301 https://$host$request_uri;
        }
    }


    # HTTPS → reverse proxy to FastAPI
    server {
        listen       443 ssl;
        server_name  localhost;
        access_log  logs/host.access.log;

        ssl_certificate      cert.pem;
        ssl_certificate_key  cert.key;
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;
        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
            proxy_pass http://api:8000;
            proxy_http_version 1.1;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout  30;
            proxy_send_timeout  120;
            send_timeout 120;
        }

        error_page  404              /404.html;
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}
