FROM python:3.14

# ENV WATCHFILES_FORCE_POLLING=true
# ENV PYTHONPATH=/api

WORKDIR /api

COPY requirements.txt .
RUN pip install --no-cache-dir --break-system-packages -r requirements.txt

EXPOSE 8000

CMD fastapi run . --host 0.0.0.0 --port 8000 --proxy-headers --workers $(nproc)